In [1]:
import numpy as np

In [35]:
#1. Write a program to create a 5 dimensional array with all zeros and ones
arr = np.random.randint(2,size=[5,5,5,5,5])
print(arr)

[[[[[0 1 1 0 0]
    [0 0 1 1 0]
    [0 1 1 1 1]
    [0 1 1 1 1]
    [1 0 1 1 0]]

   [[0 0 1 1 1]
    [1 1 0 0 0]
    [1 0 1 0 1]
    [1 0 1 1 0]
    [1 0 1 1 0]]

   [[0 0 0 1 0]
    [0 1 1 0 1]
    [0 0 1 0 0]
    [0 1 0 1 1]
    [0 0 0 1 1]]

   [[0 1 0 1 1]
    [0 1 1 1 1]
    [0 1 1 0 1]
    [0 0 0 0 0]
    [0 1 1 0 0]]

   [[1 1 0 0 0]
    [0 0 1 0 0]
    [0 1 0 0 1]
    [1 0 0 1 0]
    [0 0 0 0 0]]]


  [[[0 0 0 1 1]
    [1 1 0 1 1]
    [0 1 0 0 1]
    [0 1 0 0 1]
    [1 0 0 1 0]]

   [[1 0 0 1 0]
    [0 1 1 1 0]
    [0 1 1 1 1]
    [1 0 1 1 1]
    [1 1 0 1 0]]

   [[0 1 1 1 1]
    [0 1 0 0 0]
    [1 1 0 0 0]
    [1 0 1 1 0]
    [0 0 0 1 1]]

   [[1 0 1 0 1]
    [1 1 1 0 0]
    [1 0 1 1 0]
    [1 0 1 1 1]
    [1 1 1 0 1]]

   [[0 1 0 1 0]
    [0 1 0 0 0]
    [0 0 1 1 0]
    [0 0 1 1 0]
    [0 0 1 0 1]]]


  [[[1 0 1 1 1]
    [1 0 1 0 1]
    [0 1 0 0 0]
    [0 0 0 0 0]
    [1 0 0 0 1]]

   [[1 1 0 0 1]
    [1 1 0 0 0]
    [0 1 1 0 1]
    [0 1 0 1 1]
    [0 0 0 1 1]]

   [[1 1 0 0

In [50]:
#2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)
z = np.zeros(10, dtype = int)
o = np.ones(10, dtype = int)
f = np.full(10,5,dtype = int)
arr = np.vstack((z, o, f))
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [62]:
#3) Write a program to create a 3x4 matrix filled with values from 10 to 21
a = np.arange(10,22).reshape(3,4)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [45]:
#Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,
b = np.diag([0,1,2,3,4,5,6,7,8,9,])
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [98]:
#Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
np.flip(c,0)

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [71]:
# Write a program to reverse an array (the first element becomes the last)
d = np.array([12,13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27 ])
np.flip(d)
    

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [77]:
# Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100
e = np.arange(1,101).reshape(10,10)
s_e = []
for i in e:
    for s in i:
        if s>30 and s<80 and s%5==0:
            s_e.append(s)
print(e)

print("\nelements that are greater than 30,less than 80 and multiples of 5 are: ")
print(s_e)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

elements that are greater than 30,less than 80 and multiples of 5 are: 
[35, 40, 45, 50, 55, 60, 65, 70, 75]


In [82]:
# Write a program to create a 2D array with 1 on the border and 0 inside.
f = np.zeros((4,4),dtype = int)
f[0, :] = 1
f[-1, :] = 1
f[:, 0] = 1
f[:, -1] = 1
f

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [91]:
#Write a program to create a checkerboard pattern .Don't use default array function                                                  


In [95]:
#Write a program to find common values between two arrays.
a1 = np.array([10, 20, 40, 60])
a2 = np.array([10, 30, 40, 50])
i = np.intersect1d(a1,a2)
print(a1)
print(a2)

print("\nCommon values: \n",i)

[10 20 40 60]
[10 30 40 50]

Common values: 
 [10 40]


In [104]:
# Write a program to create an array 2d array and then reshape into 1d array
b1 = np.array([[1,2,3],[4,5,6]])
b2 = b1.reshape(-1)
print("Original array: ")
print(b1)
print("Reshaped array: ",b2)

Original array: 
[[1 2 3]
 [4 5 6]]
Reshaped array:  [1 2 3 4 5 6]


In [105]:
#Write a user defined function for creating a 1 or 2d array from scratch without using array functions
# 1-D array
N = 5
arr = [0 for i in range(N)]
print(arr)

[0, 0, 0, 0, 0]
